# Generated by Django 5.0.6 on 2026-08-06 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_identifier', models.CharField(max_length=150, verbose_name='ID o VMID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('RUNNING', 'En ejecución'), ('STOPPED', 'Detenido'), ('PAUSED', 'Pausado'), ('UNKNOWN', 'Desconocido')], default='UNKNOWN', max_length=20)),
                ('memory_limit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Límite de RAM')),
                ('cpu_cores', models.IntegerField(blank=True, null=True, verbose_name='Núcleos de CPU')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Dispositivo')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='Dirección IP')),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, verbose_name='Dirección MAC')),
                ('device_type', models.CharField(choices=[('ROUTER', 'Router'), ('SWITCH', 'Switch'), ('NVR', 'NVR / DVR'), ('CAMERA', 'Cámara IP'), ('SERVER', 'Servidor Físico'), ('OTHER', 'Otro')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('UP', 'En línea'), ('DOWN', 'Caído'), ('WARN', 'Advertencia (Latencia alta)'), ('UNKNOWN', 'Desconocido')], default='UNKNOWN', max_length=10)),
                ('is_monitored', models.BooleanField(default=True, help_text='Desmarcar para ignorar en el escaneo automático')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='Ej. DOWN, RECOVERY, HIGH_LATENCY', max_length=50)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoreo_app.container')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoreo_app.networknode')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Host (Ej. Nodo Proxmox)')),
                ('host_type', models.CharField(choices=[('PROXMOX', 'Proxmox VE'), ('DOCKER', 'Docker Daemon')], max_length=20)),
                ('api_endpoint', models.URLField(help_text='URL de la API (ej. https://192.168.1.100:8006 para Proxmox)')),
                ('api_token', models.CharField(help_text='Token de acceso o credenciales', max_length=255)),
                ('node_reference', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_host', to='monitoreo_app.networknode')),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='monitoreo_app.virtualhost'),
        ),
        migrations.CreateModel(
            name='LatencyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latency_logs', to='monitoreo_app.networknode')),
            ],
            options={
                'verbose_name': 'Registro de Latencia',
                'verbose_name_plural': 'Registros de Latencia',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['node', '-timestamp'], name='monitoreo_a_node_id_6c6e04_idx')],
            },
        ),
    ]
