# Generated by Django 5.0.6 on 2026-08-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='latencylog',
            name='packet_loss_pct',
            field=models.FloatField(default=0.0, verbose_name='% Pérdida de Paquetes'),
        ),
    ]
