# Generated by Django 5.0.6 on 2026-08-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo_app', '0002_latencylog_packet_loss_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='latencylog',
            name='inbound_mbps',
            field=models.FloatField(default=0.0, verbose_name='Tráfico de Entrada (Mbps)'),
        ),
        migrations.AddField(
            model_name='latencylog',
            name='outbound_mbps',
            field=models.FloatField(default=0.0, verbose_name='Tráfico de Salida (Mbps)'),
        ),
        migrations.AddField(
            model_name='networknode',
            name='snmp_community',
            field=models.CharField(default='public', help_text='Comunidad SNMP (ej. public)', max_length=50),
        ),
        migrations.AddField(
            model_name='networknode',
            name='snmp_enabled',
            field=models.BooleanField(default=False, verbose_name='Habilitar SNMP'),
        ),
        migrations.AddField(
            model_name='networknode',
            name='snmp_port',
            field=models.IntegerField(default=161, verbose_name='Puerto SNMP'),
        ),
    ]
