# Generated by Django 5.0.6 on 2026-08-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo_app', '0003_latencylog_inbound_mbps_latencylog_outbound_mbps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networknode',
            name='snmp_available',
            field=models.BooleanField(default=False, verbose_name='SNMP disponible'),
        ),
        migrations.AddField(
            model_name='networknode',
            name='snmp_error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Error SNMP'),
        ),
        migrations.AddField(
            model_name='networknode',
            name='snmp_last_tested',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última prueba SNMP'),
        ),
    ]
