# Generated by Django 5.0.6 on 2026-08-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo_app', '0004_networknode_snmp_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networknode',
            name='snmp_auto_discovered',
            field=models.BooleanField(default=False, verbose_name='Configuración SNMP automática'),
        ),
        migrations.AddField(
            model_name='networknode',
            name='snmp_interfaces_count',
            field=models.IntegerField(default=0, verbose_name='Interfaces SNMP detectadas'),
        ),
        migrations.AddField(
            model_name='networknode',
            name='snmp_possible_communities',
            field=models.JSONField(blank=True, default=list, verbose_name='Comunidades SNMP posibles'),
        ),
    ]
