# Generated by Django 5.0.6 on 2026-08-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo_app', '0005_networknode_snmp_auto_discovered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latencylog',
            name='inbound_mbps',
        ),
        migrations.RemoveField(
            model_name='latencylog',
            name='outbound_mbps',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='snmp_auto_discovered',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='snmp_available',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='snmp_community',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='snmp_enabled',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='snmp_error_message',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='snmp_interfaces_count',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='snmp_last_tested',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='snmp_port',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='snmp_possible_communities',
        ),
    ]
