# Generated by Django 5.0.6 on 2026-08-07 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo_app', '0006_remove_latencylog_inbound_mbps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTTPEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Servicio')),
                ('url', models.URLField(verbose_name='URL del Servicio')),
                ('expected_status', models.IntegerField(default=200, verbose_name='Código HTTP esperado')),
                ('timeout', models.IntegerField(default=5, verbose_name='Timeout (segundos)')),
                ('check_ssl', models.BooleanField(default=True, verbose_name='Verificar SSL')),
                ('status', models.CharField(choices=[('UP', 'En línea'), ('DOWN', 'Caído'), ('WARN', 'Advertencia'), ('UNKNOWN', 'Desconocido')], default='UNKNOWN', max_length=10)),
                ('last_response_time', models.FloatField(blank=True, null=True, verbose_name='Último tiempo de respuesta (ms)')),
                ('ssl_expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha expiración SSL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HTTPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(verbose_name='Tiempo de respuesta (ms)')),
                ('is_online', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ssl_valid', models.BooleanField(default=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='monitoreo_app.httpendpoint')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['endpoint', '-timestamp'], name='monitoreo_a_endpoin_eed3dd_idx')],
            },
        ),
    ]
