# Generated by Django 5.0.6 on 2026-08-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo_app', '0007_httpendpoint_httplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='httpendpoint',
            name='down_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Caído desde'),
        ),
        migrations.AddField(
            model_name='httpendpoint',
            name='recovered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recuperado a las'),
        ),
        migrations.AddField(
            model_name='networknode',
            name='down_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Caído desde'),
        ),
        migrations.AddField(
            model_name='networknode',
            name='recovered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recuperado a las'),
        ),
    ]
