# Generated by Django 5.0.6 on 2026-08-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo_app', '0008_httpendpoint_down_since_httpendpoint_recovered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='httpendpoint',
            name='notify_telegram',
            field=models.BooleanField(default=True, verbose_name='Notificar por Telegram'),
        ),
        migrations.AddField(
            model_name='networknode',
            name='notify_telegram',
            field=models.BooleanField(default=True, help_text='Enviar notificaciones por Telegram'),
        ),
    ]
