# Generated by Django 5.0.6 on 2026-08-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo_app', '0009_httpendpoint_notify_telegram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='httpendpoint',
            name='service_type',
            field=models.CharField(choices=[('API', 'API / REST API'), ('WEB', 'Sitio Web / Aplicación Web'), ('NVR_CAM', 'NVR / Cámara IP'), ('DASHBOARD', 'Dashboard / Panel Admin'), ('MONITOR', 'Monitor / Health Check'), ('DATABASE', 'Base de Datos (Web)'), ('AUTH', 'Autenticación / Login'), ('FILE', 'Servidor de Archivos'), ('EMAIL', 'Servidor de Correo'), ('DNS', 'Servidor DNS'), ('PROXY', 'Proxy / Reverse Proxy'), ('LOAD_BALANCER', 'Balanceador de Carga'), ('OTHER', 'Otro')], default='WEB', max_length=20, verbose_name='Tipo de Servicio'),
        ),
    ]
