# Generated by Django 5.0.6 on 2026-08-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo_app', '0011_alter_httpendpoint_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_bot_token', models.CharField(blank=True, help_text='Token que te proporciona @BotFather', max_length=255, null=True, verbose_name='Token del Bot de Telegram')),
                ('telegram_chat_id', models.CharField(blank=True, help_text='ID del chat donde se enviarán las notificaciones', max_length=50, null=True, verbose_name='ID del Chat de Telegram')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Configuración de la App',
                'verbose_name_plural': 'Configuraciones de la App',
            },
        ),
    ]
