# Generated by Django 5.0.6 on 2026-09-22 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo_app', '0012_appsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('OPERATOR', 'Operador'), ('VIEWER', 'Solo Lectura')], default='VIEWER', max_length=20)),
                ('telegram_bot_token', models.CharField(blank=True, help_text='Token del bot para este usuario', max_length=255, null=True, verbose_name='Token del Bot de Telegram')),
                ('telegram_chat_id', models.CharField(blank=True, help_text='ID del chat para este usuario', max_length=50, null=True, verbose_name='ID del Chat de Telegram')),
                ('notify_node_down', models.BooleanField(default=True, verbose_name='Notificar cuando un nodo cae')),
                ('notify_node_recovery', models.BooleanField(default=True, verbose_name='Notificar cuando un nodo se recupera')),
                ('notify_http_down', models.BooleanField(default=True, verbose_name='Notificar cuando un servicio cae')),
                ('notify_http_recovery', models.BooleanField(default=True, verbose_name='Notificar cuando un servicio se recupera')),
                ('notify_ssl_expiry', models.BooleanField(default=True, verbose_name='Notificar SSL por expirar')),
                ('notify_high_latency', models.BooleanField(default=True, verbose_name='Notificar latencia alta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
